"""m-mode puncture and effective source, over three evaluators and a dispatch.

    PhiSb_m = int_0^2pi N(dphib) (alpha + beta sin^2(dphib/2))^(-7/2)
              exp(-i m dphib) d dphib
    N(dphib) = sum_j ReA[j] dQ^2j + sin(dphib) sum_j ImA[j] dQ^2j
    dQ = sin(dphib/2),  alpha = alpha20 dr^2 + alpha02 dtheta^2,  C1 = alpha/beta
    PhiS_m = PhiSb_m exp(-i m (phi_p + c dr))

"ei_table" evaluates the shipped degree-(m+6) polynomial in C1 over the ReEI and
ImEI tables, for m <= EI_TABLE_MMAX. "legendre" contracts the kernel family S_mu,
generated by downward recurrence and normalised on S_0, against the Laurent
coefficients of N, for any m. "projection" takes one FFT of the pointwise
evaluator in the field-point azimuth, for m sqrt(C1) < 12.
"""

import math

import numpy as np
from scipy.special import ellipe, ellipk

from .mmode_laurent import Ld, Std, numerators, src_numerator

BRANCHES = ("auto", "ei_table", "legendre", "projection")
EI_TABLE_MMAX = 20
SWITCH_C1_COEFF = 0.5
SWITCH_C1_SRC_COEFF = 0.45
SWITCH_C1_SRC_EXP = 1.1
SWITCH_C1_EXP = 1.2
GUARD_DIGITS = 40.0
GUARD_MIN = 20
GUARD_MAX = 300000
PROJ_RESOLVE = 37.0
PROJ_NYQUIST = 1.4
PROJ_MIN_NODES = 64
SWITCH_TOL = 1e-5
EPS = np.finfo(float).eps

_LAURENT_DQ2 = {-1: -0.25, 0: 0.5, 1: -0.25}
_LAURENT_SIN = {-1: 0.5j, 1: -0.5j}


def blocks(ctx, dr, dtheta):
    """(ctx, dr, dtheta) -> (ReA[5], ImA[5]), the dQ^2j coefficients of N."""
    dr2 = dr * dr
    dr4 = dr2 * dr2
    dr6 = dr4 * dr2
    dr8 = dr4 * dr4
    dt2 = dtheta * dtheta
    dt4 = dt2 * dt2
    dt8 = dt4 * dt4
    k = ctx

    ReA = [0.0] * 5
    ImA = [0.0] * 5

    ReA[0] = ((k.A6000 + k.A7000 * dr) * dr6 + (k.A8000 + k.A9000 * dr) * dr8
              + (k.A4200 + dr * (k.A5200 + dr * (k.A6200 + k.A7200 * dr))) * dr4 * dt2
              + ((k.A2400 + k.A3400 * dr) * dr2 + (k.A4400 + k.A5400 * dr) * dr4
                 + (k.A0600 + dr * (k.A1600 + dr * (k.A2600 + k.A3600 * dr))) * dt2) * dt4
              + (k.A0800 + k.A1800 * dr) * dt8)
    ImA[0] = ((k.A6001 + k.A7001 * dr) * dr6 + k.A8001 * dr8
              + (k.A4201 + dr * (k.A5201 + k.A6201 * dr)) * dr4 * dt2
              + ((k.A2401 + k.A3401 * dr) * dr2 + k.A4401 * dr4
                 + (k.A0601 + dr * (k.A1601 + k.A2601 * dr)) * dt2) * dt4
              + k.A0801 * dt8)
    ReA[1] = ((k.A4020 + dr * (k.A5020 + dr * (k.A6020 + k.A7020 * dr))) * dr4
              + (k.A2220 + dr * (k.A3220 + dr * (k.A4220 + k.A5220 * dr))) * dr2 * dt2
              + (k.A0420 + k.A1420 * dr + (k.A2420 + k.A3420 * dr) * dr2
                 + (k.A0620 + k.A1620 * dr) * dt2) * dt4)
    ImA[1] = ((k.A4021 + dr * (k.A5021 + k.A6021 * dr)) * dr4
              + (k.A2221 + dr * (k.A3221 + k.A4221 * dr)) * dr2 * dt2
              + (k.A0421 + k.A1421 * dr + k.A2421 * dr2 + k.A0621 * dt2) * dt4)
    ReA[2] = ((k.A2040 + k.A3040 * dr) * dr2 + (k.A4040 + k.A5040 * dr) * dr4
              + (k.A0240 + dr * (k.A1240 + dr * (k.A2240 + k.A3240 * dr))) * dt2
              + (k.A0440 + k.A1440 * dr) * dt4)
    ImA[2] = ((k.A2041 + k.A3041 * dr) * dr2 + k.A4041 * dr4
              + (k.A0241 + dr * (k.A1241 + k.A2241 * dr)) * dt2 + k.A0441 * dt4)
    ReA[3] = (k.A0060 + k.A1060 * dr + (k.A2060 + k.A3060 * dr) * dr2
              + (k.A0260 + k.A1260 * dr) * dt2)
    ImA[3] = k.A0061 + k.A1061 * dr + k.A2061 * dr2 + k.A0261 * dt2
    ReA[4] = k.A0080 + k.A1080 * dr
    ImA[4] = k.A0081
    return ReA, ImA


def numerator_laurent(ReA, ImA):
    """(ReA[5], ImA[5]) -> {n: N_n} complex coefficients of N in exp(i n dphib)."""
    def mul(p, q):
        out = {}
        for a, x in p.items():
            for b, y in q.items():
                out[a + b] = out.get(a + b, 0.0 + 0.0j) + x * y
        return out

    pows = [{0: 1.0 + 0.0j}]
    for _ in range(4):
        pows.append(mul(pows[-1], _LAURENT_DQ2))

    out = {}
    for j in range(5):
        for n, v in pows[j].items():
            out[n] = out.get(n, 0.0 + 0.0j) + ReA[j] * v
        for n, v in mul(pows[j], _LAURENT_SIN).items():
            out[n] = out.get(n, 0.0 + 0.0j) + ImA[j] * v
    return out


def kernel_seed(alpha, beta, q=3):
    """(alpha, beta, q) -> S_0 = int_0^2pi (alpha + beta sin^2(t/2))^(-q-1/2) dt."""
    A = alpha + 0.5 * beta
    ab = alpha + beta
    k2 = beta / ab
    D = alpha * ab
    I_prev = 4.0 * math.sqrt(ab) * float(ellipe(k2))
    I_cur = 4.0 * float(ellipk(k2)) / math.sqrt(ab)
    p = 0.5
    while p < q:
        I_prev, I_cur = I_cur, ((2.0 * p - 1.0) * A * I_cur - (p - 1.0) * I_prev) / (p * D)
        p += 1.0
    return I_cur


def kernel_guard(C1):
    """C1 -> number of extra downward steps needed for a converged minimal solution."""
    z = 1.0 + 2.0 * C1
    ratio = z - math.sqrt(z * z - 1.0)
    decay = -math.log(ratio) if ratio < 1.0 else float("inf")
    if decay <= 0.0 or not math.isfinite(decay):
        return GUARD_MAX
    return int(min(GUARD_MAX, max(GUARD_MIN, GUARD_DIGITS / decay)))


def kernel(mumax, alpha, beta, guard=None, q=3, dtype=float):
    """(mumax, alpha, beta, q, dtype) -> S_0..S_mumax by downward recurrence on S_0.

    The seed is computed in double at any dtype.
    """
    C1 = alpha / beta
    z = dtype(1.0) + dtype(2.0) * dtype(C1)
    g = kernel_guard(C1) if guard is None else guard
    lo, hi = q - 0.5, q - 0.5
    top = mumax + g
    s = np.zeros(top + 2, dtype=dtype)
    s[top] = dtype(1e-300)
    for mu in range(top, 0, -1):
        s[mu - 1] = (dtype(2.0) * mu * z * s[mu] - (mu - lo) * s[mu + 1]) / (mu + hi)
        if abs(s[mu - 1]) > 1e250:
            s[:mu + 2] *= dtype(1e-250)
    return s[:mumax + 1] * (dtype(kernel_seed(alpha, beta, q)) / s[0])


def switch_c1(m):
    """m -> C1 above which the legendre branch is used."""
    return SWITCH_C1_COEFF / max(m, 1) ** SWITCH_C1_EXP


def choose_branch(ctx, m, dr, dtheta):
    """(ctx, m, dr, dtheta) -> "ei_table" or "legendre"."""
    if m > EI_TABLE_MMAX:
        return "legendre"
    alpha = ctx.alpha20 * dr * dr + ctx.alpha02 * dtheta * dtheta
    return "legendre" if alpha / ctx.beta > switch_c1(m) else "ei_table"


def phi_s_m_legendre(ctx, m, dr, dtheta):
    """(ctx, m, dr, dtheta) -> (Re, Im) m-mode puncture by the kernel recurrence."""
    alpha = ctx.alpha20 * dr * dr + ctx.alpha02 * dtheta * dtheta
    beta = ctx.beta
    N = numerator_laurent(*blocks(ctx, dr, dtheta))
    S = kernel(m + 5, alpha, beta)
    phiSb = sum(N[n] * S[abs(m - n)] for n in N)
    rot = complex(math.cos(m * (ctx.xp.phi + ctx.c * dr)),
                  -math.sin(m * (ctx.xp.phi + ctx.c * dr)))
    z = phiSb * rot
    return z.real, z.imag


def calc_m_legendre(ctx, m, dr, dtheta, precision="long", with_kappa=False):
    """(ctx, m, dr, dtheta, precision) -> (PhiS[2], dPhiS[8], d2PhiS[20], src[2]).

    Mixed second derivatives are NAN. With with_kappa, returns that tuple and the
    src contraction condition number sum_n |T_n S_|m-n|| / |sum_n T_n S_|m-n||.
    """
    N, dtype = (Ld, np.longdouble) if precision == "long" else (Std, float)
    num, _ = numerators(ctx, dr, dtheta, N)
    sn, _ = src_numerator(ctx, dr, dtheta, N)
    alpha = ctx.alpha20 * dr * dr + ctx.alpha02 * dtheta * dtheta
    polys = dict(num)
    polys["src"] = sn
    w_polys = {k: ({i // 2: v for i, v in poly.items() if i % 2 == 0} or {0: N.mpc(0)})
               for k, poly in polys.items()}
    deg = max(max(abs(n) for n in w) for w in w_polys.values())
    S = kernel(m + deg, alpha, ctx.beta, q=5, dtype=dtype)
    arg = N.mpf(m) * (N.mpf(ctx.xp.phi) + N.mpf(ctx.c) * N.mpf(dr))
    rot = N.mpc(N.cos(arg), -N.sin(arg))

    def mode(key):
        acc = N.mpc(0)
        for n, t in w_polys[key].items():
            acc += t * S[abs(m - n)]
        return acc * rot

    PhiS = mode("PhiS")
    d1 = [mode(k) for k in ("dt", "dr", "dth", "dph")]
    src = mode("src")
    d2 = [float("nan")] * 20
    for slot, key in ((0, "dt2"), (3, "dtph"), (4, "dr2"), (7, "dth2"), (9, "dph2")):
        v = mode(key)
        d2[2 * slot], d2[2 * slot + 1] = float(v.real), float(v.imag)
    dPhiS = []
    for v in d1:
        dPhiS += [float(v.real), float(v.imag)]
    out = ([float(PhiS.real), float(PhiS.imag)], dPhiS, d2,
           [float(src.real), float(src.imag)])
    if not with_kappa:
        return out
    terms = [t * S[abs(m - n)] for n, t in w_polys["src"].items()]
    total = sum(terms)
    return out, float(sum(abs(t) for t in terms) / abs(total))


def calc_m_ei_table(ctx_obj, m, dr, dtheta):
    """(EffsourceEquatorialContext, m, dr, dtheta) -> the shipped calc_m_offset."""
    return ctx_obj.calc_m_offset(m, dr, dtheta)


def switch_c1_src(m):
    """m -> C1 above which calc_m keeps the legendre branch for src."""
    return SWITCH_C1_SRC_COEFF / max(m, 1) ** SWITCH_C1_SRC_EXP


def projection_nodes(C1, m):
    """(C1, m) -> phi nodes for a projection sweep, rounded up to a power of two."""
    want = max(PROJ_MIN_NODES, PROJ_RESOLVE / math.sqrt(C1), PROJ_NYQUIST * m)
    return 1 << max(6, int(math.ceil(math.log2(want))))


def calc_m_projection(ctx_obj, ms, dr, dtheta, nodes=None):
    """(EffsourceEquatorialContext, m list, dr, dtheta) -> {m: (PhiS, dPhiS, d2PhiS, src)}.

    One sweep in the field-point azimuth serves every m. Valid for m sqrt(C1) < 12.
    """
    ctx = ctx_obj._ctx
    ms = [int(m) for m in ms]
    C1 = (ctx.alpha20 * dr * dr + ctx.alpha02 * dtheta * dtheta) / ctx.beta
    if C1 <= 0.0:
        raise ValueError("projection needs a field point off the particle")
    N = nodes or projection_nodes(C1, max(ms))
    psi = 2.0 * math.pi * np.arange(N) / N
    raw = [ctx_obj.calc_offset(dr, dtheta, float(x)) for x in psi]
    cols = ([np.array([r[0] for r in raw])]
            + [np.array([r[1][i] for r in raw]) for i in range(4)]
            + [np.array([r[2][i] for r in raw]) for i in range(10)]
            + [np.array([r[3] for r in raw])])
    spec = [np.fft.fft(c) / N for c in cols]
    out = {}
    for m in ms:
        rot = 2.0 * math.pi * np.exp(-1j * m * ctx.xp.phi)
        v = [sp[m % N] * rot for sp in spec]
        out[m] = ([v[0].real, v[0].imag],
                  [x for k in range(1, 5) for x in (v[k].real, v[k].imag)],
                  [x for k in range(5, 15) for x in (v[k].real, v[k].imag)],
                  [v[15].real, v[15].imag])
    return out


def calc_m(ctx_obj, m, dr, dtheta, branch="auto", tol=SWITCH_TOL):
    """(EffsourceEquatorialContext, m, dr, dtheta, branch, tol) -> (PhiS, dPhiS, d2PhiS, src, branch)."""
    if branch not in BRANCHES:
        raise ValueError(f"branch must be one of {BRANCHES}, got {branch!r}")
    ctx = ctx_obj._ctx
    if branch == "auto":
        out, kappa = calc_m_legendre(ctx, m, dr, dtheta, with_kappa=True)
        alpha = ctx.alpha20 * dr * dr + ctx.alpha02 * dtheta * dtheta
        if (kappa * EPS <= tol or m > EI_TABLE_MMAX
                or alpha / ctx.beta > switch_c1_src(m)):
            return out + ("legendre",)
        return calc_m_ei_table(ctx_obj, m, dr, dtheta) + ("ei_table",)
    if branch == "ei_table":
        if m > EI_TABLE_MMAX:
            raise ValueError(f"branch='ei_table' supports m <= {EI_TABLE_MMAX}, got {m}")
        out = calc_m_ei_table(ctx_obj, m, dr, dtheta)
    elif branch == "projection":
        out = calc_m_projection(ctx_obj, [m], dr, dtheta)[m]
    else:
        out = calc_m_legendre(ctx, m, dr, dtheta)
    return out + (branch,)


def phi_s_m_ei_table(ctx_obj, m, dr, dtheta):
    """(EffsourceEquatorialContext, m, dr, dtheta) -> (Re, Im) by the shipped closed form."""
    return ctx_obj.calc_PhiS_m_offset(m, dr, dtheta)


def phi_s_m(ctx_obj, m, dr, dtheta, branch="auto"):
    """(EffsourceEquatorialContext, m, dr, dtheta, branch) -> (Re, Im, branch used)."""
    if branch not in BRANCHES:
        raise ValueError(f"branch must be one of {BRANCHES}, got {branch!r}")
    ctx = ctx_obj._ctx
    used = choose_branch(ctx, m, dr, dtheta) if branch == "auto" else branch
    if used == "ei_table":
        if m > EI_TABLE_MMAX:
            raise ValueError(f"branch='ei_table' supports m <= {EI_TABLE_MMAX}, got {m}")
        re, im = phi_s_m_ei_table(ctx_obj, m, dr, dtheta)
    else:
        re, im = phi_s_m_legendre(ctx, m, dr, dtheta)
    return re, im, used
