#!/usr/bin/env python3
"""Generate inspectre scan config files over a parameter grid.

For each (e, p, a, mMode, nMode) combination in the sweep block below, compute the
orbital periapsis r_peri = p/(1+e) and apoapsis r_apo = p/(1-e), set the field-point
radial grid to [r_peri - R_PAD, r_apo + R_PAD], and write one .cfg into OUT_DIR.
Filenames encode all five swept params (scan_e{e}_p{p}_a{a}_m{m}_n{n}) so no two
combinations collide; each config's outfile is the matching data/<stem>.csv.

Run from the repo root (paths are relative, like submit_scans.sh / scansweep):
    python test/gen_scan_configs.py
"""
import os
import glob
import itertools
import numpy as np

# ===================== EDIT: parameter sweep ranges =====================
E_VALUES = [0.1, 0.3, 0.6]      # eccentricity      (0 <= e < 1)
P_VALUES = [8.0, 10.0, 12.0]    # semi-latus rectum
A_VALUES = [0.2, 0.5, 0.8]      # Kerr spin
M_VALUES = [2]                  # azimuthal mode mMode
N_VALUES = [2, 15]              # radial mode   nMode

R_PAD   = 2.0    # absolute padding (in M) added below r_peri and above r_apo

# ===================== EDIT: fixed config template ======================
X             = 1.0      # x = sin(theta_min); 1.0 = equatorial
R_FIELD_COUNT = 16
THETA_MIN     = 1.49     # ~ pi/2 - 0.08
THETA_MAX     = 1.65     # ~ pi/2 + 0.08
THETA_COUNT   = 12
NVALUES       = "128,256,512,1024,2048,4096,8192,16384"
EPSABS, EPSREL         = 1e-10, 1e-9
REF_EPSABS, REF_EPSREL = 1e-13, 1e-12
METHODS       = "trap,simpson,spline,minospline,fft"
REPEATS       = 1

OUT_DIR  = "test/scan_configs"
DATA_DIR = "data/sweep"
CLEAN    = True   # if True, delete existing *.cfg in OUT_DIR before writing
# ========================================================================


def g(v):
    """Compact numeric tag: 10.0 -> '10', 0.3 -> '0.3'."""
    return f"{v:g}"


def config_text(e, p, a, m, n, r_field_min, r_field_max, out_csv):
    return f"""\
# inspectre source-integration scan config (generated by gen_scan_configs.py).
# Field-point radial grid spans [r_peri - {g(R_PAD)}, r_apo + {g(R_PAD)}] with
# r_peri = p/(1+e) = {p/(1+e):.6g}, r_apo = p/(1-e) = {p/(1-e):.6g}.

# orbit
a       = {g(a)}
p       = {g(p)}
e       = {g(e)}
x       = {g(X)}
mMode   = {m}
nMode   = {n}

# field-point grid (inclusive endpoints; Count=1 uses the Min value)
rFieldMin   = {r_field_min:.10g}
rFieldMax   = {r_field_max:.10g}
rFieldCount = {R_FIELD_COUNT}
thetaMin    = {g(THETA_MIN)}
thetaMax    = {g(THETA_MAX)}
thetaCount  = {THETA_COUNT}

# fixed-grid time-resolution sweep
Nvalues = {NVALUES}

# adaptive QAG under test
epsabs = {EPSABS:g}
epsrel = {EPSREL:g}

# high-accuracy QAG ground truth
refEpsabs = {REF_EPSABS:g}
refEpsrel = {REF_EPSREL:g}

# methods to test against the reference
methods = {METHODS}

# timing: each integration is repeated this many times; the min wall time is kept
repeats = {REPEATS}

# CSV output path
outfile = {out_csv}
"""


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    if CLEAN:
        for f in glob.glob(os.path.join(OUT_DIR, "*.cfg")):
            os.remove(f)

    n_written = 0
    sample = None
    for e, p, a, m, n in itertools.product(
            E_VALUES, P_VALUES, A_VALUES, M_VALUES, N_VALUES):
        if not (0.0 <= e < 1.0):
            print(f"skip e={e}: need 0 <= e < 1 (r_apo diverges at e=1)")
            continue

        r_peri = p / (1.0 + e)
        r_apo = p / (1.0 - e)
        r_plus = 1 + np.sqrt(1-a**2)
        r_field_min = max(r_peri - R_PAD, r_plus)
        r_field_max = r_apo + R_PAD

        stem = f"scan_e{g(e)}_p{g(p)}_a{g(a)}_m{g(m)}_n{g(n)}"
        cfg_path = os.path.join(OUT_DIR, stem + ".cfg")
        out_csv = f"{DATA_DIR}/{stem}.csv"
        with open(cfg_path, "w") as fh:
            fh.write(config_text(e, p, a, m, n, r_field_min, r_field_max, out_csv))
        n_written += 1
        if sample is None:
            sample = (cfg_path, r_field_min, r_field_max)

    print(f"wrote {n_written} configs to {OUT_DIR}")
    if sample:
        print(f"  e.g. {sample[0]}: rField in [{sample[1]:.4g}, {sample[2]:.4g}]")


if __name__ == "__main__":
    main()
