#!/bin/bash

SPIN=0.5
SLRECTUM=10.0
ECC=0.2
CHI=1.0

NTIMEPTS=10
PERIODS=1
MVAL=2
NVAL=1

FIELDRADIUS=14.0
FIELDTHETA=1.5700

NRADIALPTS=40
NTHETAPTS=40

# bin/inspectre $SPIN $SLRECTUM $ECC $CHI $NTIMEPTS $PERIODS $MVAL $NVAL $NRADIALPTS $NTHETAPTS
bin/inspectre_adaptive $SPIN $SLRECTUM $ECC $CHI $NTIMEPTS $PERIODS $MVAL $NVAL $FIELDRADIUS $FIELDTHETA