from setuptools import setup, Extension
from setuptools.command.build_ext import build_ext
import os

prefix = os.environ.get("CONDA_PREFIX", "/usr")

EFF = "../effectivesource"
KERR = "../kerrgeodesic"

# The autogenerated coefficient files and the seven-channel kernel split carry
# single expressions up to 600 kB, which GCC cannot optimise in bounded memory
# (-O1 exceeds 5 GB, -O2 needs ~52 GB on the dtt file), so they are built at
# -O0. kerr-equatorial-ctx.c is deliberately NOT in this set: it holds the
# pointwise evaluator the phi-projection samples, which costs 432 ns at -O0
# against 181 ns optimised.
O0_SOURCES = {
    f"{EFF}/kerr-equatorial-split-ctx.c",
    f"{EFF}/kerr-equatorial-coeffs-ctx.c",
    f"{EFF}/kerr-equatorial-dtcoeffs-ctx.c",
    f"{EFF}/kerr-equatorial-dttcoeffs-ctx.c",
}


class build_ext_per_file_opt(build_ext):
    """Compile the listed coefficient sources at -O0, everything else at -O3."""

    def build_extension(self, ext):
        original = self.compiler._compile

        def patched(obj, src, ext_, cc_args, extra_postargs, pp_opts):
            args = list(extra_postargs)
            if os.path.normpath(src) in {os.path.normpath(s) for s in O0_SOURCES}:
                args = [a for a in args if not a.startswith("-O")] + ["-O0"]
            return original(obj, src, ext_, cc_args, args, pp_opts)

        self.compiler._compile = patched
        try:
            super().build_extension(ext)
        finally:
            self.compiler._compile = original


inspectre_c = Extension(
    "_inspectre_c",
    sources=[
        "inspectre_c.i",
        "src/inspectre_lib.c",
        f"{KERR}/korb.c",
        f"{EFF}/kerr-equatorial-ctx.c",
        f"{EFF}/kerr-equatorial-split-ctx.c",
        f"{EFF}/kerr-equatorial-coeffs-ctx.c",
        f"{EFF}/kerr-equatorial-dtcoeffs-ctx.c",
        f"{EFF}/kerr-equatorial-dttcoeffs-ctx.c",
    ],
    include_dirs=[prefix + "/include", "include", KERR, EFF],
    library_dirs=[prefix + "/lib"],
    runtime_library_dirs=[prefix + "/lib"],
    libraries=["m", "gsl", "gslcblas", "fftw3"],
    swig_opts=["-I" + KERR, "-I" + EFF, "-Iinclude"],
    extra_compile_args=["-std=gnu99", "-O3"],
)

setup(ext_modules=[inspectre_c], cmdclass={"build_ext": build_ext_per_file_opt})
